In [1]:
import pandas as pd
import requests

In [2]:
url = "https://openlibrary.org/search.json?q=author:George+R.R.+Martin"

In [3]:
response = requests.get(url)

In [4]:
data = response.json()

In [5]:
#df = pd.json_normalize(data)

In [10]:
df = pd.DataFrame(data)
df

,numFound,start,numFoundExact,docs,num_found,q,offset
0,99,0,True,"{'author_key': ['OL6787990A'], 'author_name': ...",99,author:George R.R. Martin,None
1,99,0,True,"{'author_key': ['OL6818105A'], 'author_name': ...",99,author:George R.R. Martin,None
2,99,0,True,"{'author_alternative_name': ['Denton B', 'Meli...",99,author:George R.R. Martin,None
3,99,0,True,"{'author_key': ['OL6787990A', 'OL13585934A', '...",99,author:George R.R. Martin,None
4,99,0,True,"{'author_key': ['OL6787990A', 'OL8312223A', 'O...",99,author:George R.R. Martin,None
...,...,...,...,...,...,...,...
94,99,0,True,{'author_alternative_name': ['Cory Doctorow (a...,99,author:George R.R. Martin,None
95,99,0,True,"{'author_key': ['OL6787990A', 'OL7916982A', 'O...",99,author:George R.R. Martin,None
96,99,0,True,{'author_alternative_name': ['E. Waldo Hunter'...,99,author:George R.R. Martin,None
97,99,0,True,"{'author_key': ['OL10812783A'], 'author_name':...",99,author:George R.R. Martin,None
98,99,0,True,"{'author_key': ['OL10812783A'], 'author_name':...",99,author:George R.R. Martin,None

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   numFound       99 non-null     int64
 1   start          99 non-null     int64
 2   numFoundExact  99 non-null     bool
 3   docs           99 non-null     object
 4   num_found      99 non-null     int64
 5   q              99 non-null     object
 6   offset         0 non-null      object
dtypes: bool(1), int64(3), object(3)
memory usage: 4.9+ KB